### ISSUE TITLE
Game crash on Dimension Change

### ISSUE THREAD

**Issue by jahess-it** [2piradians/Block-Armor#43]
The game crashes when players change dimensions (e.g. when they enter a Nether Portal).

- Minecraft Version: **1.18.1**
- Forge Version: **39.0.8**
- Block Armor Version: **2.6.8**

Mod List:
```
luckyblock-1.18.1-2-forge.jar, BasicNetherOres-1.18.1-7.1.0.jar, morevillagers-FORGE-1.18.1-3.1.0.jar, EnchantmentDescriptions-Forge-1.18.1-9.0.4.jar, expandedstorage-7.3.3+1.18.jar, sophisticatedbackpacks-1.18.1-3.13.6.452.jar, EasierSleeping-1.18.1-2.1.0.jar, curiouselytra-forge-1.18.1-5.0.0.1.jar, EasyMagic-v3.2.0-1.18.1-Forge.jar, jei-1.18.1-9.1.1.48.jar, PuzzlesLib-v3.1.2-1.18.1-Forge.jar, AttributeFix-Forge-1.18.1-13.0.3.jar, ninjaphenix-container-library-1.2.8+1.18.jar, caelus-forge-1.18-3.0.0.1.jar, forge-1.18.1-39.0.8-universal.jar, curios-forge-1.18.1-5.0.4.0.jar, BlockArmor-1.18.1-2.6.8.jar, Terralith_v2.0.6_Fabric+Forge.jar, gravestone-1.18.1-1.0.0.jar, comforts-forge-1.18-5.0.0.1.jar, AutoRegLib-1.7-52.jar, Quark-3.0-334.jar, polymorph-forge-1.18.1-0.33.jar
```
### Crash Report:
```
[24Dec2021 16:11:15.075] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 2
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$4223/0x0000000800b7a488@48312d3a
		2: ASM: class twopiradians.blockArmor.common.seteffect.SetEffectUndying onDimensionChange(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerChangedDimensionEvent;)V
		3: ASM: class twopiradians.blockArmor.common.seteffect.SetEffectSoft_Fall onDimensionChange(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerChangedDimensionEvent;)V
		4: ASM: class twopiradians.blockArmor.common.seteffect.SetEffectSlimey onDimensionChange(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerChangedDimensionEvent;)V
		5: ASM: class twopiradians.blockArmor.common.seteffect.SetEffectRespawn onDimensionChange(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerChangedDimensionEvent;)V
		6: ASM: class twopiradians.blockArmor.common.seteffect.SetEffectLucky onDimensionChange(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerChangedDimensionEvent;)V
		7: ASM: class twopiradians.blockArmor.common.seteffect.SetEffectLightweight onDimensionChange(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerChangedDimensionEvent;)V
		8: ASM: class twopiradians.blockArmor.common.seteffect.SetEffectHoarder onDimensionChange(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerChangedDimensionEvent;)V
		9: ASM: class twopiradians.blockArmor.common.seteffect.SetEffectHealth_Boost onDimensionChange(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerChangedDimensionEvent;)V
		10: ASM: class twopiradians.blockArmor.common.seteffect.SetEffectFiery onDimensionChange(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerChangedDimensionEvent;)V
		11: ASM: class twopiradians.blockArmor.common.seteffect.SetEffectAutoSmelt onDimensionChange(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerChangedDimensionEvent;)V
		12: ASM: class twopiradians.blockArmor.common.seteffect.SetEffect onDimensionChange(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerChangedDimensionEvent;)V
java.lang.ExceptionInInitializerError
	at TRANSFORMER/blockarmor@2.6.8/twopiradians.blockArmor.common.seteffect.SetEffect.onDimensionChange(SetEffect.java:247)
	at net.minecraftforge.eventbus.ASMEventHandler_38_SetEffect_onDimensionChange_PlayerChangedDimensionEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@39.0.8/net.minecraftforge.event.ForgeEventFactory.firePlayerChangedDimensionEvent(ForgeEventFactory.java:805)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ServerPlayer.changeDimension(ServerPlayer.java:746)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.Entity.m_5489_(Entity.java:2248)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.Entity.m_20157_(Entity.java:1880)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.Entity.m_6075_(Entity.java:427)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.LivingEntity.m_6075_(LivingEntity.java:317)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.Entity.m_8119_(Entity.java:410)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2205)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.player.Player.m_8119_(Player.java:234)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:206)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.network.Connection.m_129483_(Connection.java:233)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:86)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: net.minecraftforge.fml.util.ObfuscationReflectionHelper$UnknownConstructorException: Could not find constructor 'CooldownInstance(ItemCooldowns, int, int)' in class net.minecraft.world.item.ItemCooldowns$CooldownInstance
	at LAYER PLUGIN/fmlcore@1.18.1-39.0.8/net.minecraftforge.fml.util.ObfuscationReflectionHelper.findConstructor(ObfuscationReflectionHelper.java:207)
	at TRANSFORMER/blockarmor@2.6.8/twopiradians.blockArmor.packet.SSyncCooldownsPacket.<clinit>(SSyncCooldownsPacket.java:24)
	... 24 more

[16:11:15] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:145) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:86) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ExceptionInInitializerError
	at twopiradians.blockArmor.common.seteffect.SetEffect.onDimensionChange(SetEffect.java:247) ~[BlockArmor-1.18.1-2.6.8.jar%2355!:1.18.1-2.6.8]
	at net.minecraftforge.eventbus.ASMEventHandler_38_SetEffect_onDimensionChange_PlayerChangedDimensionEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?]
	at net.minecraftforge.event.ForgeEventFactory.firePlayerChangedDimensionEvent(ForgeEventFactory.java:805) ~[forge-1.18.1-39.0.8-universal.jar%2378!:?]
	at net.minecraft.server.level.ServerPlayer.changeDimension(ServerPlayer.java:746) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.world.entity.Entity.m_5489_(Entity.java:2248) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.world.entity.Entity.m_20157_(Entity.java:1880) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.world.entity.Entity.m_6075_(Entity.java:427) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.world.entity.LivingEntity.m_6075_(LivingEntity.java:317) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.world.entity.Entity.m_8119_(Entity.java:410) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2205) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:234) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:206) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:233) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	... 6 more
Caused by: net.minecraftforge.fml.util.ObfuscationReflectionHelper$UnknownConstructorException: Could not find constructor 'CooldownInstance(ItemCooldowns, int, int)' in class net.minecraft.world.item.ItemCooldowns$CooldownInstance
	at net.minecraftforge.fml.util.ObfuscationReflectionHelper.findConstructor(ObfuscationReflectionHelper.java:207) ~[fmlcore-1.18.1-39.0.8.jar%2375!:?]
	at twopiradians.blockArmor.packet.SSyncCooldownsPacket.<clinit>(SSyncCooldownsPacket.java:24) ~[BlockArmor-1.18.1-2.6.8.jar%2355!:1.18.1-2.6.8]
	at twopiradians.blockArmor.common.seteffect.SetEffect.onDimensionChange(SetEffect.java:247) ~[BlockArmor-1.18.1-2.6.8.jar%2355!:1.18.1-2.6.8]
	at net.minecraftforge.eventbus.ASMEventHandler_38_SetEffect_onDimensionChange_PlayerChangedDimensionEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?]
	at net.minecraftforge.event.ForgeEventFactory.firePlayerChangedDimensionEvent(ForgeEventFactory.java:805) ~[forge-1.18.1-39.0.8-universal.jar%2378!:?]
	at net.minecraft.server.level.ServerPlayer.changeDimension(ServerPlayer.java:746) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.world.entity.Entity.m_5489_(Entity.java:2248) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.world.entity.Entity.m_20157_(Entity.java:1880) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.world.entity.Entity.m_6075_(Entity.java:427) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.world.entity.LivingEntity.m_6075_(LivingEntity.java:317) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.world.entity.Entity.m_8119_(Entity.java:410) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2205) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:234) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:206) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:233) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.18.1-20211210.034407-srg.jar%2374!:?]
	... 6 more
```

**Comment by Furgl** [comment]
Fixed in v2.6.9 - thanks for reporting it!
